api_platform:
    title: Chijal API
    version: 1.0.2
    defaults:
        url_generation_strategy: 0
        stateless: false
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']

