api_platform:
    title: Batsi API
    version: 1.0.01
    defaults:
        url_generation_strategy: 0
        stateless: false
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']

