# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    trusted_proxies:
      # https://www.cloudflare.com/ips/
       -        REMOTE_ADDR,
       -        127.0.0.1,
       -        173.245.48.0/20
       -        103.21.244.0/22
       -        103.22.200.0/22
       -        103.31.4.0/22
       -        141.101.64.0/18
       -        108.162.192.0/18
       -        190.93.240.0/20
       -        188.114.96.0/20
       -        197.234.240.0/22
       -        198.41.128.0/17
       -        162.158.0.0/15
       -        104.16.0.0/13
       -        104.24.0.0/14
       -        172.64.0.0/13
       -        131.0.72.0/22'
       -    # https://symfony.com/doc/current/deployment/proxies.html
    trusted_headers: ['forwarded', 'x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-prefix']
    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
