# Default configuration for extension with alias: "survos_media"
survos_media:
    default_locale:       en
    cache_ttl:            3600
    sais_integration:     true
    media_server:
        apiKey:               null
        resize_path:          '/media/{preset}/{id}'
        host:                 '%env(MEDIARY_ENDPOINT)%'
