twig:
    file_name_pattern: '*.twig'
    globals:
        mobile_base: '%env(MOBILE_BASE_URL)%'
    form_themes:
        - 'bootstrap_5_horizontal_layout.html.twig'

when@test:
    twig:
        strict_variables: true
