twig:
    file_name_pattern: '*.twig'
    globals:
        mobile_base: '%env(MOBILE_BASE_URL)%'
        spreadsheetId: '%env(GOOGLE_SPREADSHEET_ID)%'
        voxitourEndpoint: '%env(VOXiTOUR_ENDPOINT)%'

    form_themes:
        - 'bootstrap_5_horizontal_layout.html.twig'

when@test:
    twig:
        strict_variables: true
