<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250407224925 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE artist_translation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, bio TEXT DEFAULT NULL, locale VARCHAR(5) NOT NULL, translatable_id INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_9D53F3282C2AC5D3 ON artist_translation (translatable_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX artist_translation_unique_translation ON artist_translation (translatable_id, locale)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE obj (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE artist_translation ADD CONSTRAINT FK_9D53F3282C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES artist (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE artist ADD languages JSON DEFAULT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE location ADD marking VARCHAR(32) DEFAULT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE obra ADD type VARCHAR(32) DEFAULT NULL
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE artist_translation DROP CONSTRAINT FK_9D53F3282C2AC5D3
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE artist_translation
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE obj
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE location DROP marking
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE artist DROP languages
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE obra DROP type
        SQL);
    }
}
