<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250827144730 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE artist (code VARCHAR(32) NOT NULL, name VARCHAR(255) NOT NULL, birth_year INT DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, phone VARCHAR(24) DEFAULT NULL, instagram VARCHAR(255) DEFAULT NULL, bio_backing TEXT DEFAULT NULL, slogan_backing TEXT DEFAULT NULL, obra_count INT DEFAULT NULL, languages JSON DEFAULT NULL, gender VARCHAR(22) DEFAULT NULL, social TEXT DEFAULT NULL, drive_url VARCHAR(1024) DEFAULT NULL, youtube_url VARCHAR(1024) DEFAULT NULL, audio_code VARCHAR(128) DEFAULT NULL, image_codes JSON DEFAULT NULL, PRIMARY KEY (code))');
        $this->addSql('CREATE TABLE location (code VARCHAR(32) NOT NULL, name VARCHAR(255) NOT NULL, address VARCHAR(255) DEFAULT NULL, type VARCHAR(255) DEFAULT NULL, obra_count INT DEFAULT NULL, status VARCHAR(255) DEFAULT NULL, contact_name VARCHAR(255) DEFAULT NULL, phone VARCHAR(64) DEFAULT NULL, marking VARCHAR(32) DEFAULT NULL, lat DOUBLE PRECISION DEFAULT NULL, lng DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY (code))');
        $this->addSql('CREATE TABLE media (code VARCHAR(255) NOT NULL, resized JSON DEFAULT NULL, type VARCHAR(255) NOT NULL, original_url TEXT DEFAULT NULL, mime_type VARCHAR(255) DEFAULT NULL, size INT DEFAULT NULL, original_width INT DEFAULT NULL, original_height INT DEFAULT NULL, status_code INT DEFAULT NULL, blur VARCHAR(255) DEFAULT NULL, context JSON DEFAULT NULL, exif JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, marking VARCHAR(32) DEFAULT NULL, PRIMARY KEY (code))');
        $this->addSql('CREATE TABLE obj (id VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE obra (code VARCHAR(32) NOT NULL, title VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, year INT DEFAULT NULL, width INT DEFAULT NULL, height INT DEFAULT NULL, depth INT DEFAULT NULL, materials VARCHAR(255) DEFAULT NULL, price INT DEFAULT NULL, type VARCHAR(32) DEFAULT NULL, size VARCHAR(255) DEFAULT NULL, drive_url VARCHAR(1024) DEFAULT NULL, youtube_url VARCHAR(1024) DEFAULT NULL, audio_code VARCHAR(128) DEFAULT NULL, image_codes JSON DEFAULT NULL, location_code VARCHAR(32) DEFAULT NULL, artist_code VARCHAR(32) NOT NULL, PRIMARY KEY (code))');
        $this->addSql('CREATE INDEX IDX_2EEE6DBDF71185D8 ON obra (location_code)');
        $this->addSql('CREATE INDEX IDX_2EEE6DBDCBABB607 ON obra (artist_code)');
        $this->addSql('CREATE TABLE sacro (id VARCHAR(255) NOT NULL, notes VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, label VARCHAR(255) DEFAULT NULL, extra JSON DEFAULT NULL, flickr_url VARCHAR(255) DEFAULT NULL, flickr_info JSON DEFAULT NULL, sais_id VARCHAR(255) DEFAULT NULL, image_sizes JSON DEFAULT NULL, drive_url VARCHAR(255) DEFAULT NULL, marking VARCHAR(32) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE str (hash VARCHAR(64) NOT NULL, original TEXT NOT NULL, src_locale VARCHAR(8) NOT NULL, context VARCHAR(128) DEFAULT NULL, meta JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (hash))');
        $this->addSql('CREATE TABLE str_translation (meta JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, hash VARCHAR(64) NOT NULL, locale VARCHAR(8) NOT NULL, text TEXT DEFAULT NULL, PRIMARY KEY (hash, locale))');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) DEFAULT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, is_verified BOOLEAN NOT NULL, code VARCHAR(48) NOT NULL, name VARCHAR(255) DEFAULT NULL, cel VARCHAR(255) DEFAULT NULL, is_artist BOOLEAN DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON users (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE obra ADD CONSTRAINT FK_2EEE6DBDF71185D8 FOREIGN KEY (location_code) REFERENCES location (code) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE obra ADD CONSTRAINT FK_2EEE6DBDCBABB607 FOREIGN KEY (artist_code) REFERENCES artist (code) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE obra DROP CONSTRAINT FK_2EEE6DBDF71185D8');
        $this->addSql('ALTER TABLE obra DROP CONSTRAINT FK_2EEE6DBDCBABB607');
        $this->addSql('DROP TABLE artist');
        $this->addSql('DROP TABLE location');
        $this->addSql('DROP TABLE media');
        $this->addSql('DROP TABLE obj');
        $this->addSql('DROP TABLE obra');
        $this->addSql('DROP TABLE sacro');
        $this->addSql('DROP TABLE str');
        $this->addSql('DROP TABLE str_translation');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
