<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250529183301 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            DROP SEQUENCE easy_media__folder_id_seq CASCADE
        SQL);
        $this->addSql(<<<'SQL'
            DROP SEQUENCE easy_media__media_id_seq CASCADE
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE easy_media__media
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE easy_media__folder
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE artist ADD drive_url VARCHAR(255) DEFAULT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE artist ADD images JSON DEFAULT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE artist ADD preferred_pronoun VARCHAR(255) DEFAULT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE artist ADD on_social VARCHAR(255) DEFAULT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE artist ADD preferred_contact VARCHAR(255) DEFAULT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE artist ADD studio_open VARCHAR(255) DEFAULT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE artist ADD tags JSON DEFAULT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE artist ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE artist ALTER id DROP DEFAULT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE artist ALTER id ADD GENERATED BY DEFAULT AS IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE artist_translation ADD slogan VARCHAR(255) DEFAULT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE artist_translation ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE artist_translation ALTER id DROP DEFAULT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE artist_translation ALTER id ADD GENERATED BY DEFAULT AS IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE location ADD status VARCHAR(255) DEFAULT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE location ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE location ALTER id DROP DEFAULT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE location ALTER id ADD GENERATED BY DEFAULT AS IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE obj ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE obj ALTER id DROP DEFAULT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE obj ALTER id ADD GENERATED BY DEFAULT AS IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE obra DROP audio
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE obra ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE obra ALTER id DROP DEFAULT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE obra ALTER id ADD GENERATED BY DEFAULT AS IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE obra_image ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE obra_image ALTER id DROP DEFAULT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE obra_image ALTER id ADD GENERATED BY DEFAULT AS IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE obra_image ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN obra_image.created_at IS ''
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE sacro_translation ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE sacro_translation ALTER id DROP DEFAULT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE sacro_translation ALTER id ADD GENERATED BY DEFAULT AS IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE sacro_translation ALTER translatable_id TYPE VARCHAR
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE users ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE users ALTER id DROP DEFAULT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE users ALTER id ADD GENERATED BY DEFAULT AS IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE messenger_messages ALTER id DROP DEFAULT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE messenger_messages ALTER id ADD GENERATED BY DEFAULT AS IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE messenger_messages ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE messenger_messages ALTER available_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE messenger_messages ALTER delivered_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN messenger_messages.created_at IS ''
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN messenger_messages.available_at IS ''
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN messenger_messages.delivered_at IS ''
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE SEQUENCE easy_media__folder_id_seq INCREMENT BY 1 MINVALUE 1 START 1
        SQL);
        $this->addSql(<<<'SQL'
            CREATE SEQUENCE easy_media__media_id_seq INCREMENT BY 1 MINVALUE 1 START 1
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE easy_media__media (id INT DEFAULT easy_media__media_id_seq NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(100) NOT NULL, mime VARCHAR(255) DEFAULT NULL, size INT DEFAULT NULL, last_modified INT DEFAULT NULL, metas JSON NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE easy_media__folder (id INT DEFAULT easy_media__folder_id_seq NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(100) NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE obj ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE obj ALTER id SET DEFAULT obj_id_seq
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE obj ALTER id DROP IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE users ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE users ALTER id SET DEFAULT users_id_seq
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE users ALTER id DROP IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE messenger_messages ALTER id SET DEFAULT messenger_messages_id_seq
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE messenger_messages ALTER id DROP IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE messenger_messages ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE messenger_messages ALTER available_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE messenger_messages ALTER delivered_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN messenger_messages.created_at IS '(DC2Type:datetime_immutable)'
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN messenger_messages.available_at IS '(DC2Type:datetime_immutable)'
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN messenger_messages.delivered_at IS '(DC2Type:datetime_immutable)'
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE artist DROP drive_url
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE artist DROP images
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE artist DROP preferred_pronoun
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE artist DROP on_social
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE artist DROP preferred_contact
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE artist DROP studio_open
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE artist DROP tags
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE artist ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE artist ALTER id SET DEFAULT artist_id_seq
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE artist ALTER id DROP IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE location DROP status
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE location ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE location ALTER id SET DEFAULT location_id_seq
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE location ALTER id DROP IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE artist_translation DROP slogan
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE artist_translation ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE artist_translation ALTER id SET DEFAULT artist_translation_id_seq
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE artist_translation ALTER id DROP IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE sacro_translation ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE sacro_translation ALTER id SET DEFAULT sacro_translation_id_seq
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE sacro_translation ALTER id DROP IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE sacro_translation ALTER translatable_id TYPE VARCHAR(255)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE obra_image ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE obra_image ALTER id SET DEFAULT obra_image_id_seq
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE obra_image ALTER id DROP IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE obra_image ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN obra_image.created_at IS '(DC2Type:datetime_immutable)'
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE obra ADD audio TEXT DEFAULT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE obra ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE obra ALTER id SET DEFAULT obra_id_seq
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE obra ALTER id DROP IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN obra.audio IS '(DC2Type:easy_media_type)'
        SQL);
    }
}
