<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260519141046 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE altos_obj (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, cons INT DEFAULT NULL, code VARCHAR(80) NOT NULL, museo_procedencia VARCHAR(120) DEFAULT NULL, location VARCHAR(255) DEFAULT NULL, location2 VARCHAR(255) DEFAULT NULL, title_es VARCHAR(255) DEFAULT NULL, title_tzh VARCHAR(255) DEFAULT NULL, title_tl VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, description_tzh TEXT DEFAULT NULL, tecnica VARCHAR(255) DEFAULT NULL, medidas VARCHAR(255) DEFAULT NULL, image TEXT DEFAULT NULL, image_s3 TEXT DEFAULT NULL, fotografia VARCHAR(120) DEFAULT NULL, value_display VARCHAR(64) DEFAULT NULL, ubi VARCHAR(120) DEFAULT NULL, loc_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_altosobj_code ON altos_obj (code)');
        $this->addSql('CREATE INDEX idx_altosobj_museo ON altos_obj (museo_procedencia)');
        $this->addSql('CREATE INDEX idx_altosobj_loc ON altos_obj (loc_id)');
        $this->addSql('CREATE TABLE artist (code VARCHAR(32) NOT NULL, name VARCHAR(255) NOT NULL, birth_year INT DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, phone VARCHAR(24) DEFAULT NULL, instagram VARCHAR(255) DEFAULT NULL, bio_backing TEXT DEFAULT NULL, slogan_backing TEXT DEFAULT NULL, obra_count INT DEFAULT NULL, languages JSON DEFAULT NULL, gender VARCHAR(22) DEFAULT NULL, social TEXT DEFAULT NULL, drive_url VARCHAR(1024) DEFAULT NULL, youtube_url VARCHAR(1024) DEFAULT NULL, audio_code VARCHAR(128) DEFAULT NULL, image_codes JSON DEFAULT NULL, PRIMARY KEY (code))');
        $this->addSql('CREATE TABLE babel_term (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(120) NOT NULL, path VARCHAR(512) NOT NULL, label_code VARCHAR(64) NOT NULL, description_code VARCHAR(64) DEFAULT NULL, rules JSONB NOT NULL, meta JSONB NOT NULL, enabled BOOLEAN NOT NULL, sort INT DEFAULT NULL, term_set_id INT NOT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_77FE42F2F3AD3475 ON babel_term (term_set_id)');
        $this->addSql('CREATE INDEX IDX_77FE42F2727ACA70 ON babel_term (parent_id)');
        $this->addSql('CREATE UNIQUE INDEX term_term_set_code_uq ON babel_term (term_set_id, code)');
        $this->addSql('CREATE UNIQUE INDEX term_term_set_path_uq ON babel_term (term_set_id, path)');
        $this->addSql('CREATE TABLE index_info (index_name VARCHAR(255) NOT NULL, last_indexed TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, document_count INT NOT NULL, settings JSONB NOT NULL, task_id VARCHAR(255) DEFAULT NULL, primary_key VARCHAR(255) NOT NULL, batch_id VARCHAR(255) DEFAULT NULL, status VARCHAR(20) DEFAULT NULL, label VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, aggregator VARCHAR(255) DEFAULT NULL, institution VARCHAR(255) DEFAULT NULL, country VARCHAR(255) DEFAULT NULL, locale VARCHAR(255) DEFAULT NULL, PRIMARY KEY (index_name))');
        $this->addSql('CREATE TABLE loc (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(80) DEFAULT NULL, type VARCHAR(40) NOT NULL, label VARCHAR(255) NOT NULL, subtitle VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_loc_type ON loc (type)');
        $this->addSql('CREATE UNIQUE INDEX uniq_loc_code ON loc (code)');
        $this->addSql('CREATE TABLE location (code VARCHAR(32) NOT NULL, name VARCHAR(255) NOT NULL, address VARCHAR(255) DEFAULT NULL, barrio VARCHAR(255) DEFAULT NULL, type VARCHAR(255) DEFAULT NULL, obra_count INT DEFAULT NULL, status VARCHAR(255) DEFAULT NULL, contact_name VARCHAR(255) DEFAULT NULL, phone VARCHAR(64) DEFAULT NULL, marking VARCHAR(32) DEFAULT NULL, pending_steps JSON DEFAULT \'{}\' NOT NULL, lat DOUBLE PRECISION DEFAULT NULL, lng DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY (code))');
        $this->addSql('CREATE TABLE media (id VARCHAR(32) NOT NULL, status VARCHAR(255) NOT NULL, provider VARCHAR(100) DEFAULT NULL, external_id VARCHAR(255) DEFAULT NULL, external_url TEXT DEFAULT NULL, raw_data JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, s3_url TEXT DEFAULT NULL, small_url TEXT DEFAULT NULL, storage_key TEXT DEFAULT NULL, location JSON DEFAULT NULL, tags JSON NOT NULL, width INT DEFAULT NULL, height INT DEFAULT NULL, duration INT DEFAULT NULL, file_size BIGINT DEFAULT NULL, mime_type VARCHAR(100) DEFAULT NULL, title TEXT DEFAULT NULL, description TEXT DEFAULT NULL, type VARCHAR(255) NOT NULL, camera VARCHAR(255) DEFAULT NULL, exif_data JSON DEFAULT NULL, taken_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, view_count INT DEFAULT NULL, like_count INT DEFAULT NULL, chapters JSON DEFAULT NULL, subtitles JSON DEFAULT NULL, artist VARCHAR(255) DEFAULT NULL, album VARCHAR(255) DEFAULT NULL, bitrate INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE obj (id VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE obra (code VARCHAR(32) NOT NULL, title VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, year INT DEFAULT NULL, width INT DEFAULT NULL, height INT DEFAULT NULL, depth INT DEFAULT NULL, materials VARCHAR(255) DEFAULT NULL, price INT DEFAULT NULL, type VARCHAR(32) DEFAULT NULL, size VARCHAR(255) DEFAULT NULL, exhibition VARCHAR(128) DEFAULT NULL, drive_url VARCHAR(1024) DEFAULT NULL, youtube_url VARCHAR(1024) DEFAULT NULL, audio_code VARCHAR(128) DEFAULT NULL, image_codes JSON DEFAULT NULL, location_code VARCHAR(32) DEFAULT NULL, artist_code VARCHAR(32) NOT NULL, PRIMARY KEY (code))');
        $this->addSql('CREATE INDEX IDX_2EEE6DBDF71185D8 ON obra (location_code)');
        $this->addSql('CREATE INDEX IDX_2EEE6DBDCBABB607 ON obra (artist_code)');
        $this->addSql('CREATE TABLE sacro (id VARCHAR(255) NOT NULL, notes VARCHAR(255) DEFAULT NULL, extra JSON DEFAULT NULL, flickr_url VARCHAR(255) DEFAULT NULL, flickr_info JSON DEFAULT NULL, sais_id VARCHAR(255) DEFAULT NULL, image_sizes JSON DEFAULT NULL, drive_url VARCHAR(255) DEFAULT NULL, label_backing VARCHAR(255) NOT NULL, description_backing TEXT DEFAULT NULL, marking VARCHAR(32) DEFAULT NULL, pending_steps JSON DEFAULT \'{}\' NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE str (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(64) NOT NULL, source_locale VARCHAR(10) NOT NULL, source TEXT NOT NULL, context VARCHAR(80) DEFAULT NULL, meta JSONB DEFAULT \'[]\' NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX str_ctx_idx ON str (context)');
        $this->addSql('CREATE INDEX str_src_locale_idx ON str (source_locale)');
        $this->addSql('CREATE INDEX str_src_locale_ctx_idx ON str (source_locale, context)');
        $this->addSql('CREATE UNIQUE INDEX str_code_uq ON str (code)');
        $this->addSql('CREATE TABLE str_tr (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, str_code VARCHAR(64) NOT NULL, target_locale VARCHAR(10) NOT NULL, engine VARCHAR(20) DEFAULT NULL, text TEXT DEFAULT NULL, status VARCHAR(16) DEFAULT \'new\' NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, meta JSONB DEFAULT \'[]\' NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX str_tr_target_locale_idx ON str_tr (target_locale)');
        $this->addSql('CREATE INDEX str_tr_str_code_idx ON str_tr (str_code)');
        $this->addSql('CREATE UNIQUE INDEX str_tr_uq ON str_tr (str_code, target_locale, engine)');
        $this->addSql('CREATE TABLE term_set (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(80) NOT NULL, label_code VARCHAR(64) NOT NULL, description_code VARCHAR(64) DEFAULT NULL, rules JSONB NOT NULL, meta JSONB NOT NULL, enabled BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX term_set_code_uq ON term_set (code)');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) DEFAULT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, is_verified BOOLEAN NOT NULL, code VARCHAR(48) NOT NULL, name VARCHAR(255) DEFAULT NULL, cel VARCHAR(255) DEFAULT NULL, is_artist BOOLEAN DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON users (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE altos_obj ADD CONSTRAINT FK_5FEBF59F6505CAD1 FOREIGN KEY (loc_id) REFERENCES loc (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE babel_term ADD CONSTRAINT FK_77FE42F2F3AD3475 FOREIGN KEY (term_set_id) REFERENCES term_set (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE babel_term ADD CONSTRAINT FK_77FE42F2727ACA70 FOREIGN KEY (parent_id) REFERENCES babel_term (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE obra ADD CONSTRAINT FK_2EEE6DBDF71185D8 FOREIGN KEY (location_code) REFERENCES location (code) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE obra ADD CONSTRAINT FK_2EEE6DBDCBABB607 FOREIGN KEY (artist_code) REFERENCES artist (code) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE altos_obj DROP CONSTRAINT FK_5FEBF59F6505CAD1');
        $this->addSql('ALTER TABLE babel_term DROP CONSTRAINT FK_77FE42F2F3AD3475');
        $this->addSql('ALTER TABLE babel_term DROP CONSTRAINT FK_77FE42F2727ACA70');
        $this->addSql('ALTER TABLE obra DROP CONSTRAINT FK_2EEE6DBDF71185D8');
        $this->addSql('ALTER TABLE obra DROP CONSTRAINT FK_2EEE6DBDCBABB607');
        $this->addSql('DROP TABLE altos_obj');
        $this->addSql('DROP TABLE artist');
        $this->addSql('DROP TABLE babel_term');
        $this->addSql('DROP TABLE index_info');
        $this->addSql('DROP TABLE loc');
        $this->addSql('DROP TABLE location');
        $this->addSql('DROP TABLE media');
        $this->addSql('DROP TABLE obj');
        $this->addSql('DROP TABLE obra');
        $this->addSql('DROP TABLE sacro');
        $this->addSql('DROP TABLE str');
        $this->addSql('DROP TABLE str_tr');
        $this->addSql('DROP TABLE term_set');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
