<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250820165542 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE artist (name VARCHAR(255) NOT NULL, birth_year INT DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, code VARCHAR(32) NOT NULL, instagram VARCHAR(255) DEFAULT NULL, obra_count INT DEFAULT NULL, social_media TEXT DEFAULT NULL, studio_address TEXT DEFAULT NULL, studio_visitable VARCHAR(32) DEFAULT NULL, languages JSON DEFAULT NULL, gender VARCHAR(22) DEFAULT NULL, social TEXT DEFAULT NULL, timestamp TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, pronouns VARCHAR(16) DEFAULT NULL, phone VARCHAR(24) DEFAULT NULL, contact_method VARCHAR(255) DEFAULT NULL, studio VARCHAR(28) DEFAULT NULL, headshot VARCHAR(255) DEFAULT NULL, types VARCHAR(255) DEFAULT NULL, slogan VARCHAR(255) DEFAULT NULL, drive_url TEXT DEFAULT NULL, preferred_pronoun VARCHAR(255) DEFAULT NULL, on_social VARCHAR(255) DEFAULT NULL, preferred_contact VARCHAR(255) DEFAULT NULL, studio_open VARCHAR(255) DEFAULT NULL, tags JSON DEFAULT NULL, id VARCHAR(255) NOT NULL, image_codes JSON DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_159968777153098 ON artist (code)');
        $this->addSql('CREATE TABLE artist_translation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, bio TEXT DEFAULT NULL, slogan VARCHAR(255) DEFAULT NULL, locale VARCHAR(5) NOT NULL, translatable_id VARCHAR DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9D53F3282C2AC5D3 ON artist_translation (translatable_id)');
        $this->addSql('CREATE UNIQUE INDEX artist_translation_unique_translation ON artist_translation (translatable_id, locale)');
        $this->addSql('CREATE TABLE location (name VARCHAR(255) NOT NULL, address VARCHAR(255) DEFAULT NULL, code VARCHAR(255) NOT NULL, type VARCHAR(24) DEFAULT NULL, obra_count INT DEFAULT NULL, lat DOUBLE PRECISION DEFAULT NULL, lng DOUBLE PRECISION DEFAULT NULL, status VARCHAR(255) DEFAULT NULL, id VARCHAR(255) NOT NULL, marking VARCHAR(32) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE media (code VARCHAR(255) NOT NULL, resized JSON DEFAULT NULL, type VARCHAR(255) NOT NULL, original_url TEXT DEFAULT NULL, mime_type VARCHAR(255) DEFAULT NULL, size INT DEFAULT NULL, original_width INT DEFAULT NULL, original_height INT DEFAULT NULL, status_code INT DEFAULT NULL, blur VARCHAR(255) DEFAULT NULL, context JSON DEFAULT NULL, exif JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, marking VARCHAR(32) DEFAULT NULL, PRIMARY KEY (code))');
        $this->addSql('CREATE TABLE obj (id VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE obra (description TEXT DEFAULT NULL, year INT DEFAULT NULL, width INT DEFAULT NULL, height INT DEFAULT NULL, depth INT DEFAULT NULL, materials VARCHAR(255) DEFAULT NULL, price INT DEFAULT NULL, type VARCHAR(32) DEFAULT NULL, audio_code VARCHAR(255) DEFAULT NULL, drive_url TEXT DEFAULT NULL, youtube_url VARCHAR(255) DEFAULT NULL, size VARCHAR(255) DEFAULT NULL, code VARCHAR(255) NOT NULL, title VARCHAR(255) DEFAULT NULL, image_codes JSON DEFAULT NULL, location_id VARCHAR DEFAULT NULL, artist_id VARCHAR NOT NULL, PRIMARY KEY (code))');
        $this->addSql('CREATE INDEX IDX_2EEE6DBD64D218E ON obra (location_id)');
        $this->addSql('CREATE INDEX IDX_2EEE6DBDB7970CF8 ON obra (artist_id)');
        $this->addSql('CREATE TABLE sacro (id VARCHAR(255) NOT NULL, extra JSON DEFAULT NULL, flickr_url VARCHAR(255) DEFAULT NULL, flickr_info JSON DEFAULT NULL, sais_id VARCHAR(255) DEFAULT NULL, image_sizes JSON DEFAULT NULL, drive_url VARCHAR(255) DEFAULT NULL, marking VARCHAR(32) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE sacro_translation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, notes VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, label VARCHAR(255) DEFAULT NULL, locale VARCHAR(5) NOT NULL, translatable_id VARCHAR DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_89281EBB2C2AC5D3 ON sacro_translation (translatable_id)');
        $this->addSql('CREATE UNIQUE INDEX sacro_translation_unique_translation ON sacro_translation (translatable_id, locale)');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) DEFAULT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, is_verified BOOLEAN NOT NULL, code VARCHAR(48) NOT NULL, name VARCHAR(255) DEFAULT NULL, cel VARCHAR(255) DEFAULT NULL, is_artist BOOLEAN DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON users (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE artist_translation ADD CONSTRAINT FK_9D53F3282C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES artist (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE obra ADD CONSTRAINT FK_2EEE6DBD64D218E FOREIGN KEY (location_id) REFERENCES location (id)');
        $this->addSql('ALTER TABLE obra ADD CONSTRAINT FK_2EEE6DBDB7970CF8 FOREIGN KEY (artist_id) REFERENCES artist (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sacro_translation ADD CONSTRAINT FK_89281EBB2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES sacro (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE artist_translation DROP CONSTRAINT FK_9D53F3282C2AC5D3');
        $this->addSql('ALTER TABLE obra DROP CONSTRAINT FK_2EEE6DBD64D218E');
        $this->addSql('ALTER TABLE obra DROP CONSTRAINT FK_2EEE6DBDB7970CF8');
        $this->addSql('ALTER TABLE sacro_translation DROP CONSTRAINT FK_89281EBB2C2AC5D3');
        $this->addSql('DROP TABLE artist');
        $this->addSql('DROP TABLE artist_translation');
        $this->addSql('DROP TABLE location');
        $this->addSql('DROP TABLE media');
        $this->addSql('DROP TABLE obj');
        $this->addSql('DROP TABLE obra');
        $this->addSql('DROP TABLE sacro');
        $this->addSql('DROP TABLE sacro_translation');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
