<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260302204637 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE altos_obj (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, cons INT DEFAULT NULL, code VARCHAR(80) NOT NULL, museo_procedencia VARCHAR(120) DEFAULT NULL, location VARCHAR(255) DEFAULT NULL, location2 VARCHAR(255) DEFAULT NULL, title_es VARCHAR(255) DEFAULT NULL, title_tzh VARCHAR(255) DEFAULT NULL, title_tl VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, description_tzh TEXT DEFAULT NULL, tecnica VARCHAR(255) DEFAULT NULL, medidas VARCHAR(255) DEFAULT NULL, image TEXT DEFAULT NULL, image_s3 TEXT DEFAULT NULL, fotografia VARCHAR(120) DEFAULT NULL, value_display VARCHAR(64) DEFAULT NULL, ubi VARCHAR(120) DEFAULT NULL, loc_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_altosobj_code ON altos_obj (code)');
        $this->addSql('CREATE INDEX idx_altosobj_museo ON altos_obj (museo_procedencia)');
        $this->addSql('CREATE INDEX idx_altosobj_loc ON altos_obj (loc_id)');
        $this->addSql('CREATE TABLE loc (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(80) DEFAULT NULL, type VARCHAR(40) NOT NULL, label VARCHAR(255) NOT NULL, subtitle VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_loc_type ON loc (type)');
        $this->addSql('CREATE UNIQUE INDEX uniq_loc_code ON loc (code)');
        $this->addSql('ALTER TABLE altos_obj ADD CONSTRAINT FK_5FEBF59F6505CAD1 FOREIGN KEY (loc_id) REFERENCES loc (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE obra ADD exhibition VARCHAR(128) DEFAULT NULL');
        $this->addSql('ALTER TABLE sacro ADD label_backing VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE sacro DROP label');
        $this->addSql('ALTER TABLE sacro RENAME COLUMN description TO description_backing');
        $this->addSql('ALTER TABLE str ADD status VARCHAR(32) DEFAULT NULL');
        $this->addSql('ALTER TABLE str ADD locale_statuses JSONB DEFAULT NULL');
        $this->addSql('ALTER TABLE str ALTER meta TYPE JSONB');
        $this->addSql('ALTER TABLE str_translation DROP CONSTRAINT str_translation_pkey');
        $this->addSql('ALTER TABLE str_translation ADD status VARCHAR(32) DEFAULT NULL');
        $this->addSql('ALTER TABLE str_translation ADD str_hash VARCHAR(32) NOT NULL');
        $this->addSql('ALTER TABLE str_translation ALTER hash TYPE VARCHAR(40)');
        $this->addSql('ALTER TABLE str_translation ADD PRIMARY KEY (hash)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE altos_obj DROP CONSTRAINT FK_5FEBF59F6505CAD1');
        $this->addSql('DROP TABLE altos_obj');
        $this->addSql('DROP TABLE loc');
        $this->addSql('ALTER TABLE obra DROP exhibition');
        $this->addSql('ALTER TABLE sacro ADD label VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE sacro DROP label_backing');
        $this->addSql('ALTER TABLE sacro RENAME COLUMN description_backing TO description');
        $this->addSql('ALTER TABLE str DROP status');
        $this->addSql('ALTER TABLE str DROP locale_statuses');
        $this->addSql('ALTER TABLE str ALTER meta TYPE JSON');
        $this->addSql('ALTER TABLE str_translation DROP CONSTRAINT str_translation_pkey');
        $this->addSql('ALTER TABLE str_translation DROP status');
        $this->addSql('ALTER TABLE str_translation DROP str_hash');
        $this->addSql('ALTER TABLE str_translation ALTER hash TYPE VARCHAR(64)');
        $this->addSql('ALTER TABLE str_translation ADD PRIMARY KEY (hash, locale)');
    }
}
